openshift/httpd/deployment.yaml
openshift/httpd/namespace.yaml
openshift/httpd/pvc.yaml
openshift/httpd/route.yaml
openshift/httpd/service.yaml

HTTPD Implementation

---

openshift/auth/group-sync-github-secret.yaml
openshift/auth/group-sync-operator-namespace.yaml
openshift/auth/group-sync-operator-operatorgroup.yaml
openshift/auth/group-sync-operator-subscription.yaml
openshift/auth/groupsync.yaml
openshift/auth/oauth-github-secret.yaml
openshift/auth/oauth.yaml
openshift/catalogs/redhatgov-catalogsource.yaml
openshift/nexus/namespace.yaml
openshift/nexus/nexus-operatorgroup.yaml
openshift/nexus/nexus-subscription.yaml
openshift/nexus/nexus.yml
openshift/rbac/rfe-cluster-admins-clusterrolebinding.yaml

Auth and Nexus configurations
* GitHub based Authentication (restricted on CoP Team)
* Group Synchronization (GitHub org. Cluster Admin role applied to RFE team)
* Deployment of Nexus as repository)

Auth and Nexus configurations

---

openshift/nexus/nexus-setup-job.yaml

Nexus setup job to create repositories

Nexus setup job

---

openshift/gitops/clusters/overlays/rhpds/argocd/configs/cnv-app-patch.yaml
openshift/gitops/clusters/overlays/rhpds/argocd/configs/kustomization.yaml
openshift/gitops/clusters/overlays/rhpds/configs/cnv/kubevirt-config-configmap.yaml
openshift/gitops/clusters/overlays/rhpds/configs/cnv/kustomization.yaml

Added debug emulation CM

---

openshift/gitops/environments/overlays/rfe/kustomization.yaml
openshift/gitops/manifests/rfe/rbac/base/kustomization.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-automation-role.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-automation-rolebinding.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-serviceaccount.yaml

RFE Automation RBAC

---

openshift/gitops/manifests/rfe/nexus/base/nexus-setup-job.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-automation-role.yaml

Configures privileges and user to tie into pipeline

Management of Nexus assets

---

openshift/gitops/manifests/rfe/nexus/base/nexus-setup-job.yaml
openshift/gitops/manifests/rfe/nexus/base/nexus.yaml

Corrected Nexus setup job

---

hello-world/blueprint.toml

Hello World blueprint

---

openshift/gitops/manifests/rfe/ansible-rfe-runner/base/ansible-rfe-runner-buildconfig.yaml

Added kubectl to Ansible Builder

Added kubectl to Ansible Builder

---

openshift/gitops/manifests/rfe/nexus/base/nexus-setup-job.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-automation-role.yaml

* Corrected logic in job
* Added Exec permission for `rfe-automation` SA

Updates to Nexus setup job

---

openshift/gitops/environments/overlays/configs/kustomization.yaml
openshift/gitops/environments/overlays/rfe/kustomization.yaml
openshift/gitops/manifests/argocd/apps/pipelines/base/kustomization.yaml
openshift/gitops/manifests/argocd/apps/pipelines/base/pipelines-app.yaml
openshift/gitops/manifests/configs/pipelines/base/config-defaults-configmap.yaml
openshift/gitops/manifests/configs/pipelines/base/kustomization.yaml
openshift/gitops/manifests/configs/pipelines/base/namespace.yaml
openshift/gitops/manifests/rfe/pipelines/build-rfe-task.yaml
openshift/gitops/manifests/rfe/pipelines/download-upload-rfe-task.yaml
openshift/gitops/manifests/rfe/pipelines/kustomization.yaml
openshift/gitops/manifests/rfe/pipelines/rfe-kickstart-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/rfe-tarball-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/upload-kickstart-task.yaml
openshift/gitops/manifests/rfe/pipelines/volumeclaimtemplate.yaml

Cluster deployment and RFE pipeline assets

OpenShift Pipeline resources

---

ansible/ansible.cfg
ansible/playbooks/build-rfe-rpm-ostree.yaml
ansible/playbooks/download-upload-rfe-artifact.yaml
ansible/playbooks/upload-kickstart.yaml
ansible/roles/build-rpm-ostree/defaults/main.yaml
ansible/roles/build-rpm-ostree/tasks/main.yaml
ansible/roles/content-download-upload/defaults/main.yml
ansible/roles/content-download-upload/tasks/download-rfe-rpm-ostree.yaml
ansible/roles/content-download-upload/tasks/upload-rfe-artifact.yaml

Automation to support building RFE image and publishing RFE image and kickstart

Added ansible build/upload assets

---

ansible/playbooks/build-rfe-rpm-ostree.yaml
ansible/playbooks/download-upload-rfe-artifact.yaml

Fix openshift-image-builder-imi role

Fix openshift-image-builder-imi role

---

openshift/gitops/clusters/overlays/self/argocd/rfe/nexus-app-patch.yaml

Fix Nexus Spelling

---

openshift/gitops/clusters/overlays/shared/argocd/configs/kustomization.yaml
openshift/gitops/manifests/bootstrap/argocd/base/argocd.yaml

Changes to align with patched resources

Changes to align with patched resources

---

openshift/gitops/clusters/overlays/self/rfe/nexus/nexus-patch.yaml
openshift/gitops/clusters/overlays/shared/rfe/nexus/nexus-patch.yaml

Nexus refactor

---

openshift/gitops/clusters/overlays/shared/argocd/configs/kustomization.yaml
openshift/gitops/clusters/overlays/shared/argocd/configs/rbac-app-patch.yaml

Added shared cluster config for RBAC

Added shared cluster config for RBAC

---

ansible/roles/content-download-upload/defaults/main.yml
ansible/roles/content-download-upload/tasks/upload-rfe-artifact.yaml
openshift/gitops/manifests/rfe/pipelines/base/download-upload-rfe-task.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-kickstart-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-tarball-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/base/upload-kickstart-task.yaml
openshift/gitops/manifests/rfe/rbac/base/rfe-automation-role.yaml

Assets to support pipeline results

Assets to support pipeline results

---

ibm-weather-forecaster/kickstart.ks

Kickstart for ibm-weather-forecaster

ibm-weather-forecaster kickstart

---

openshift/gitops/clusters/overlays/shared/rfe/nexus/nexus-patch.yaml

Changed andrewWithTheRedHat username

Changed andrewWithTheRedHat username

---

openshift/gitops/manifests/rfe/httpd/base/deployment.yaml

Updated HTTPD resources

---

.github/linters/.markdown-lint.yml

Added linter file to disable linting for line length (MD013) as well as in line HTML (MD033).

updated lint rules to disable 13 and 33 (inline html and line length)

---

openshift/gitops/manifests/rfe/nexus/base/kustomization.yaml
openshift/gitops/manifests/rfe/nexus/base/nexus-setup-job.yaml
openshift/gitops/manifests/rfe/nexus/base/nexus-setup-role.yaml
openshift/gitops/manifests/rfe/nexus/base/nexus-setup-rolebinding.yaml
openshift/gitops/manifests/rfe/nexus/base/nexus-setup-serviceaccount.yaml

Fixes for Nexus operator changes

Fixes for Nexus operator changes

---

openshift/gitops/environments/overlays/configs/kustomization.yaml
openshift/gitops/manifests/argocd/apps/configs/ocs/base/kustomization.yaml
openshift/gitops/manifests/argocd/apps/configs/ocs/base/ocs-app.yaml
openshift/gitops/manifests/configs/ocs/base/kustomization.yaml
openshift/gitops/manifests/configs/ocs/base/namespace.yaml
openshift/gitops/manifests/configs/ocs/base/noobaa.yaml
openshift/gitops/manifests/configs/ocs/base/operatorgroup.yaml
openshift/gitops/manifests/configs/ocs/base/subscription.yaml

Added OCS components

---

openshift/gitops/manifests/configs/pipelines/base/kustomization.yaml
openshift/gitops/manifests/configs/pipelines/base/subscription.yaml

Added pipelines subscription

---

openshift/gitops/clusters/overlays/byo/argocd/manager/cluster-config-manager-app.yaml
openshift/gitops/clusters/overlays/byo/argocd/manager/rfe-app.yaml
openshift/gitops/clusters/overlays/shared/argocd/manager/cluster-config-manager-app.yaml
openshift/gitops/clusters/overlays/shared/argocd/manager/rfe-app.yaml
openshift/gitops/manifests/argocd/apps/configs/auth/base/auth-app.yaml
openshift/gitops/manifests/argocd/apps/configs/catalogsources/base/catalogsources-app.yaml
openshift/gitops/manifests/argocd/apps/configs/cnv/base/cnv-app.yaml
openshift/gitops/manifests/argocd/apps/configs/ocs/base/ocs-app.yaml
openshift/gitops/manifests/argocd/apps/configs/pipelines/base/pipelines-app.yaml
openshift/gitops/manifests/argocd/apps/configs/quay/base/quay-app.yaml
openshift/gitops/manifests/argocd/apps/configs/rbac/base/rbac-app.yaml
openshift/gitops/manifests/argocd/apps/configs/sealed-secrets/base/sealed-secrets-app.yaml
openshift/gitops/manifests/argocd/apps/configs/user-workload-monitoring/base/user-workload-monitoring-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/ansible-rfe-runner/base/ansible-rfe-runner-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/httpd/base/httpd-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/image-builder-vm/base/image-builder-vm-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/nexus/base/nexus-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/pipelines/base/pipelines-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/rbac/base/rbac-app.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-iso-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-kickstart-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-tarball-pipeline.yaml

Added v1 app revision

---

openshift/gitops/environments/overlays/bootstrap/kustomization.yaml
openshift/gitops/manifests/argocd/project/bootstrap/base/kustomization.yaml
openshift/gitops/manifests/argocd/project/cluster-configs/base/kustomization.yaml
openshift/gitops/manifests/argocd/project/rfe/base/kustomization.yaml

Fixed issue with namespace for bootstrap

Fixed issue with namespace for bootstrap

---

openshift/gitops/manifests/configs/auth/base/oauth-patch.yaml

Avoid race condition

---

openshift/gitops/clusters/overlays/byo/configs/auth/kustomization.yaml
openshift/gitops/clusters/overlays/byo/configs/auth/oauth.yaml

Avoids conflict of htpasswd secret

Avoids conflict of htpasswd secret

---

openshift/gitops/manifests/configs/quay/base/rfe-automation-role-quay.yaml
openshift/gitops/manifests/configs/quay/base/rfe-automation-rolebinding-quay.yaml

Adding moved Quay RBAC files

---

openshift/gitops/manifests/bootstrap/argocd/base/argocd.yaml

Setting explicit resources for ArgoCD repo pod

Setting explicit resources for ArgoCD repo pod

---

openshift/gitops/manifests/argocd/apps/configs/cnv/base/cnv-app.yaml
openshift/gitops/manifests/argocd/apps/rfe/image-builder-vm/base/image-builder-vm-app.yaml
openshift/gitops/manifests/configs/cnv/base/hyperconverged.yaml
openshift/gitops/manifests/rfe/image-builder-vm/base/image-builder-vm.yaml
openshift/gitops/manifests/rfe/image-builder-vm/base/redhat-image-downloader-ansible-job.yaml

Addresses 1 and 2 in issue #126.

Adjusting Argo CD sync parameters for cnv/image-builder apps.

---

charts/application-manager/templates/_helpers.tpl
charts/application-manager/templates/application.yaml
helm/testing/operators/sealed-secret-operator.yaml

Deploys sealed-secrets using the helm chart directly.

Added sealed-secrets helm application

---

charts/user-workload-monitoring/Chart.yaml
charts/user-workload-monitoring/templates/cluster-monitoring-config.yaml
charts/user-workload-monitoring/templates/user-workload-monitoring-config.yaml
charts/user-workload-monitoring/values.yaml
helm/testing/user-workload-monitoring/user-workload-monitoring.yaml

Adds the User Workload Monitoring helm chart.
@sabre1041 @nasx please review at your discretion.
/Jordi

Adding User Workload Monitoring Helm Chart

---

ansible/roles/iso-generator/defaults/main.yaml
ansible/roles/redhat-image-downloader/defaults/main.yaml
openshift/gitops/manifests/rfe/image-builder-vm/base/image-builder-vm.yaml

Rhel85 helm migration

---

charts/user-workload-monitoring/values.yaml

Fixed spelling of user workload monitoring

Fix user workload monitoring

---

charts/oauth/Chart.yaml
charts/oauth/templates/merge-oauth-identity-provider-configmap.yaml
charts/oauth/templates/merge-oauth-identity-providers-job.yaml
charts/oauth/templates/merge-oauth-identity-providers-rfe-oauth-secret.yaml
charts/oauth/templates/merge-oauth-identity-providers-role-rolebinding.yaml
charts/oauth/templates/merge-oauth-identity-providers-role-serviceaccount.yaml
charts/oauth/templates/merge-oauth-identity-providers-role.yaml
charts/oauth/values.yaml
helm/testing/oauth/oauth.yaml

Defines the helm chart that contains the OAuth job responsible for merging the different OAuth providers required to operate ArgoCD.
@sabre1041 @nasx please review at your discretion.

Added gitops-oauth Helm Chart

---

charts/catalogsources/templates/redhatgov-catalogsource.yaml
charts/catalogsources/values.yaml

Added updateStrategy to CatalogSource

Added updateStrategy to CatalogSource

---

charts/image-builder-vm/Chart.yaml
charts/image-builder-vm/templates/_helpers.tpl
charts/image-builder-vm/templates/image-builder-vm-ansible-job.yaml
charts/image-builder-vm/templates/image-builder-vm-service.yaml
charts/image-builder-vm/templates/image-builder-vm.yaml
charts/image-builder-vm/templates/redhat-image-downloader-ansible-job.yaml
charts/image-builder-vm/values.yaml
helm/testing/image-builder-vm/image-builder-vm.yaml

Adds the image-builder-vm charts.
@sabre1041 @nasx please review.

Adding image-builder-vm chart

---

charts/bootstrap/templates/redhat-portal-credentials-secret.yaml
charts/bootstrap/values.yaml
charts/nexus/templates/nexus-setup-job.yaml

- Adding Image Builder VM chart to bootstrap
- Disabling strict content type validation in Nexus repositories

Image Builder VM Updates

---

charts/rfe-pipelines/values.yaml

@sabre1041 @nasx please take a look

Prevent pipelineRuns from being pruned

---

.github/workflows/lint.yml

Changed the name of the linting job

---

charts/argocd/templates/argocd.yaml

@sabre1041 @nasx please review.

Fix typo in installplan and build health status

---

charts/rfe-pipelines/templates/rfe-oci-publish-content-pipeline.yaml
openshift/gitops/manifests/rfe/pipelines/base/rfe-oci-publish-content-pipeline.yaml

Added types to all pipeline parameters

Added types to all pipeline parameters

---

docs/basic-walkthrough.md

Changed path for volumeclaimtemplate.yaml file

---

ansible/roles/oci-stage-content/tasks/main.yaml

Removed merge conflict artifact

Removed merge conflict artifact

---

README.md
examples/values/deployment/disable-odf.yaml

@nasx @sabre1041 please review.

Adds the ODF operator as disabled component

---

ansible/roles/image-builder/defaults/main.yml
ansible/roles/image-builder/tasks/add-composer-source.yaml
ansible/roles/image-builder/tasks/composer-sources.yaml
ansible/roles/image-builder/tasks/main.yaml
ansible/roles/image-builder/templates/composer-source.toml.j2
charts/image-builder-vm/templates/composer-configmap.yaml
charts/image-builder-vm/templates/image-builder-vm-ansible-job.yaml
charts/image-builder-vm/values.yaml
ct.yaml

Support for adding composer sources to resolve #215 
Example Helm `values`
```yaml
---
application-manager:
charts:
rfe-automation:
values:
charts:
rfe:
values:
charts:
image-builder-vm:
name: image-builder-vm
values:
imageBuilderVM:
composer:
sources:
- id: "transmission"
name: "Transmission"
type: "yum-baseurl"
url: "http://cdn.redhat.edge-lab.net/content/rpms/rhel/8"
check_gpg: false
check_ssl: false
system: false
```

Support for adding composer sources

---

ansible/playbooks/configure-image-builder.yaml
charts/image-builder-vm/templates/image-builder-vm-ansible-job.yaml

Several enhancements:
* Corrected `activeDeadlineSeconds` to be part of the image builder Job Template
* Management of Entitlement Secrets

Entitlements enhancements

---

microshift/kickstart.ks

Added microshift kickstart

---

microshift/blueprint.toml

Added MicroShift blueprint

---

charts/httpd/templates/httpd-ostree-buildconfig.yaml

First disable all repositories and then enable the list one by one

HTTPD Build Config - fix enabled repos list

---

charts/bootstrap/values.yaml

Update Quay to 3.6

---

microshift/kickstart.ks

Updated microshift user password

Updated microshift user password

---

charts/bootstrap/values.yaml
charts/pulp/Chart.yaml
charts/pulp/templates/_helpers.tpl
charts/pulp/templates/objectbucketclaim.yaml
charts/pulp/templates/patch-operator/clusterrole.yaml
charts/pulp/templates/patch-operator/clusterrolebinding.yaml
charts/pulp/templates/patch-operator/patch.yaml
charts/pulp/templates/patch-operator/serviceaccount.yaml
charts/pulp/templates/pulp.yaml
charts/pulp/templates/s3-storage-secret.yaml
charts/pulp/values.yaml

Pulp chart

---

charts/argocd/templates/argocd.yaml
charts/operator/templates/operatorgroup.yaml
charts/operator/values.yaml
setup/init.sh
setup/values-init.yaml

Migration of ArgoCD to v1beta1

Migration of ArgoCD to v1beta1

---

.github/workflows/lint.yml
charts/cnv/values.yaml
charts/odf/values.yaml
setup/values-init.yaml

Corrected references to namespace chart dependency

Corrected references to namespace chart dependency
